### ISSUE TITLE
Missing input file

### ISSUE THREAD

**Issue by GinnyAquarius** [pachterlab/kallisto_paper_analysis#3]
Hi Harold,
Where have you added the new file? I haven't seen any change on github. Thank you very much!

**Comment by pimentel** [comment]
ah. sorry about that. I committed and the push failed. turns out the file is too large for github. although, it looks like this file is automatically generated from the pipeline. are you running things from `run_all.sh` in the main directory? also, did you turn off the ` --dryrun` argument in the script?

**Comment by pimentel** [comment]
ps: still investigating this further

**Comment by GinnyAquarius** [comment]
Hi I tried as your instruction but I still have problem with network connection
http://lmcb.math.berkeley.edu/kallisto/NA12716.fa
Connecting to lmcb.math.berkeley.edu|128.32.183.17|:80... failed: Connection timed out.
Can I download needed files from any other source?

**Comment by pimentel** [comment]
@GinnyAquarius that is definitely a problem... we have had some networking failures and it seems like that server is down.

If you replace any reference to `http://lmcb.math.berkeley.edu` to `http://128.32.142.223` it should work now. this server is temporary so I don't want to change it in the main branch. I'm trying to find a more permanent location for it.

**Comment by GinnyAquarius** [comment]
Thank you very much!

**Comment by kspham** [comment]
The link is not working!
